-- CreateTable
CREATE TABLE `Likeds` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `userId` INTEGER NOT NULL,
    `postId` INTEGER NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `Likeds` ADD CONSTRAINT `Likeds_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `cl_users`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
