const countries = [
    { id: 1, name: "Afeganistão" },
    { id: 2, name: "África do Sul" },
    { id: 3, name: "Albânia" },
    { id: 4, name: "Alemanha" },
    { id: 5, name: "Andorra" },
    { id: 6, name: "Angola" },
    { id: 7, name: "Antígua e Barbuda" },
    { id: 8, name: "Arábia Saudita" },
    { id: 9, name: "Argélia" },
    { id: 10, name: "Argentina" },
    { id: 11, name: "Armênia" },
    { id: 12, name: "Austrália" },
    { id: 13, name: "Áustria" },
    { id: 14, name: "Azerbaijão" },
    { id: 15, name: "Bahamas" },
    { id: 16, name: "Bahrein" },
    { id: 17, name: "Bangladesh" },
    { id: 18, name: "Barbados" },
    { id: 19, name: "Bielorrússia" },
    { id: 20, name: "Bélgica" },
    { id: 21, name: "Belize" },
    { id: 22, name: "Benin" },
    { id: 23, name: "Birmânia" },
    { id: 24, name: "Bocás del Toro" },
    { id: 25, name: "Bósnia e Herzegovina" },
    { id: 26, name: "Botsuana" },
    { id: 27, name: "Brasil" },
    { id: 28, name: "Brunei" },
    { id: 29, name: "Bulgária" },
    { id: 30, name: "Burkina Faso" },
    { id: 31, name: "Burundi" },
    { id: 32, name: "Cabo Verde" },
    { id: 33, name: "Camarões" },
    { id: 34, name: "Camboja" },
    { id: 35, name: "Canadá" },
    { id: 36, name: "Catar" },
    { id: 37, name: "Cazaquistão" },
    { id: 38, name: "Cingapura" },
    { id: 39, name: "Colômbia" },
    { id: 40, name: "Comores" },
    { id: 41, name: "Congo, República do" },
    { id: 42, name: "Congo, República Democrática do" },
    { id: 43, name: "Coreia do Norte" },
    { id: 44, name: "Coreia do Sul" },
    { id: 45, name: "Costa do Marfim" },
    { id: 46, name: "Costa Rica" },
    { id: 47, name: "Croácia" },
    { id: 48, name: "Cuba" },
    { id: 49, name: "Dinamarca" },
    { id: 50, name: "Djibuti" },
    { id: 51, name: "Dominica" },
    { id: 52, name: "República Dominicana" },
    { id: 53, name: "Egito" },
    { id: 54, name: "El Salvador" },
    { id: 55, name: "Emirados Árabes Unidos" },
    { id: 56, name: "Equador" },
    { id: 57, name: "Eritreia" },
    { id: 58, name: "Eslováquia" },
    { id: 59, name: "Eslovênia" },
    { id: 60, name: "Espanha" },
    { id: 61, name: "Estados Unidos" },
    { id: 62, name: "Estônia" },
    { id: 63, name: "Eswatini" },
    { id: 64, name: "Etiópia" },
    { id: 65, name: "Fiji" },
    { id: 66, name: "Filipinas" },
    { id: 67, name: "Finlândia" },
    { id: 68, name: "França" },
    { id: 69, name: "Gana" },
    { id: 70, name: "Geórgia" },
    { id: 71, name: "Alemanha" },
    { id: 72, name: "Gibraltar" },
    { id: 73, name: "Grécia" },
    { id: 74, name: "Grenada" },
    { id: 75, name: "Guatemala" },
    { id: 76, name: "Guiana" },
    { id: 77, name: "Guiné" },
    { id: 78, name: "Guiné-Bissau" },
    { id: 79, name: "Guiné Equatorial" },
    { id: 80, name: "Honduras" },
    { id: 81, name: "Hungria" },
    { id: 82, name: "Iémen" },
    { id: 83, name: "Ilhas Cayman" },
    { id: 84, name: "Ilhas Cook" },
    { id: 85, name: "Ilhas Faroe" },
    { id: 86, name: "Ilhas Marshall" },
    { id: 87, name: "Ilhas Maurício" },
    { id: 88, name: "Ilhas Salomão" },
    { id: 89, name: "Ilhas Virgens Britânicas" },
    { id: 90, name: "Ilhas Virgens Americanas" },
    { id: 91, name: "Índia" },
    { id: 92, name: "Indonésia" },
    { id: 93, name: "Irã" },
    { id: 94, name: "Iraque" },
    { id: 95, name: "Irlanda" },
    { id: 96, name: "Islândia" },
    { id: 97, name: "Itália" },
    { id: 98, name: "Jamaica" },
    { id: 99, name: "Japão" },
    { id: 100, name: "Jordânia" },
    { id: 101, name: "Kazajistão" },
    { id: 102, name: "Quênia" },
    { id: 103, name: "Kiribati" },
    { id: 104, name: "Kuwait" },
    { id: 105, name: "Laos" },
    { id: 106, name: "Lesoto" },
    { id: 107, name: "Letônia" },
    { id: 108, name: "Líbano" },
    { id: 109, name: "Libéria" },
    { id: 110, name: "Líbia" },
    { id: 111, name: "Liechtenstein" },
    { id: 112, name: "Lituânia" },
    { id: 113, name: "Luxemburgo" },
    { id: 114, name: "Malásia" },
    { id: 115, name: "Malawi" },
    { id: 116, name: "Maldivas" },
    { id: 117, name: "Mali" },
    { id: 118, name: "Malta" },
    { id: 119, name: "Marrocos" },
    { id: 120, name: "Mauritânia" },
    { id: 121, name: "México" },
    { id: 122, name: "Moçambique" },
    { id: 123, name: "Moldávia" },
    { id: 124, name: "Monaco" },
    { id: 125, name: "Mongólia" },
    { id: 126, name: "Montenegro" },
    { id: 127, name: "Namíbia" },
    { id: 128, name: "Nepal" },
    { id: 129, name: "Nicarágua" },
    { id: 130, name: "Nigéria" },
    { id: 131, name: "Noruega" },
    { id: 132, name: "Nova Zelândia" },
    { id: 133, name: "Omã" },
    { id: 134, name: "Paquistão" },
    { id: 135, name: "Panamá" },
    { id: 136, name: "Papua Nova Guiné" },
    { id: 137, name: "Paraguai" },
    { id: 138, name: "Países Baixos" },
    { id: 139, name: "Peru" },
    { id: 140, name: "Polônia" },
    { id: 141, name: "Portugal" },
    { id: 142, name: "Quirguistão" },
    { id: 143, name: "República Checa" },
    { id: 144, name: "República do Congo" },
    { id: 145, name: "República Dominicana" },
    { id: 146, name: "Romênia" },
    { id: 147, name: "Ruanda" },
    { id: 148, name: "Rússia" },
    { id: 149, name: "Saara Ocidental" },
    { id: 150, name: "Samoa" },
    { id: 151, name: "San Marino" },
    { id: 152, name: "Santa Lúcia" },
    { id: 153, name: "São Cristóvão e Névis" },
    { id: 154, name: "São Tomé e Príncipe" },
    { id: 155, name: "Senegal" },
    { id: 156, name: "Serra Leoa" },
    { id: 157, name: "Sérvia" },
    { id: 158, name: "Singapura" },
    { id: 159, name: "Síria" },
    { id: 160, name: "Somália" },
    { id: 161, name: "Sri Lanka" },
    { id: 162, name: "Suécia" },
    { id: 163, name: "Suíça" },
    { id: 164, name: "Suriname" },
    { id: 165, name: "Tailândia" },
    { id: 166, name: "Taiwan" },
    { id: 167, name: "Tajiquistão" },
    { id: 168, name: "Tanzânia" },
    { id: 169, name: "Togo" },
    { id: 170, name: "Tonga" },
    { id: 171, name: "Trinidad e Tobago" },
    { id: 172, name: "Tunísia" },
    { id: 173, name: "Turcomenistão" },
    { id: 174, name: "Turquia" },
    { id: 175, name: "Tuvalu" },
    { id: 176, name: "Ucrânia" },
    { id: 177, name: "Uganda" },
    { id: 178, name: "Uruguai" },
    { id: 179, name: "Uzbequistão" },
    { id: 180, name: "Vanuatu" },
    { id: 181, name: "Vaticano" },
    { id: 182, name: "Venezuela" },
    { id: 183, name: "Zâmbia" },
    { id: 184, name: "Zimbábue" }
];

export default countries;